### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by TS-CUBED** [jfbercher/jupyter_latex_envs#47]
Hi,

First of all, thanks for the great extension. WIth this I can write my next paper completely in jupyter (SageMath kernel) and only do the final edit in the LateX editor.

The extension seems to be incompatible with python3, though? I upgraded jupyter to the python3 version and installed the python3 version of the nbextensions and everything works in the notebook.

But the export to latex with nbconvert (--to latex-with-lenvs) fails. I reverted back to python2 and everything seems fine.

Is the latex-environment extension compatible with python3, yet?

Thanks 
Torsten

**Comment by TS-CUBED** [comment]
Error message: 

pandoc: Duplicate link reference `[//]' "source" (line 5, column 1)
Traceback (most recent call last):
  File "/home/acests3/sage-8.8/local/bin/jupyter-nbconvert", line 11, in <module>
    sys.exit(main())
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 338, in start
    self.convert_notebooks()
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 508, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 479, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 408, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/latex_envs/latex_envs.py", line 543, in from_notebook_node
    postout = self.postprocess(output)
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/latex_envs/latex_envs.py", line 528, in postprocess
    nb_text = self.tocrefrm(nb_text)
  File "/home/acests3/sage-8.8/local/lib/python3.7/site-packages/latex_envs/latex_envs.py", line 504, in tocrefrm
    newtext = re.sub('\\\\begin{center}\\\\rule{[\S\s]*?\\\\end{center}[\s]*?\S*\href{toc.ipynb}{Index}[\S\s ]*?.ipynb}{Next}', '', newtext, flags=re.M)  # noqa
  File "/home/acests3/sage-8.8/local/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/home/acests3/sage-8.8/local/lib/python3.7/re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/home/acests3/sage-8.8/local/lib/python3.7/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/home/acests3/sage-8.8/local/lib/python3.7/sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/home/acests3/sage-8.8/local/lib/python3.7/sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "/home/acests3/sage-8.8/local/lib/python3.7/sre_parse.py", line 507, in _parse
    code = _escape(source, this, state)
  File "/home/acests3/sage-8.8/local/lib/python3.7/sre_parse.py", line 402, in _escape
    raise source.error("bad escape %s" % escape, len(escape))
re.error: bad escape \h at position 52

**Comment by errosica** [comment]
Also getting the same error when using Python3.  This package is really neat. It would be great if this was fixed.

**Comment by errosica** [comment]
After doing a little [research](https://stackoverflow.com/questions/54330673/how-to-fix-error-bad-escape-u-at-position-0), it seems changing line 504 of latex_envs.py to the following fixes the problem:
 
`newtext = re.sub('\\\\begin{center}\\\\rule{[\S\s]*?\\\\end{center}[\s]*?\S*\\\\href{toc.ipynb}{Index}[\S\s ]*?.ipynb}{Next}', '', newtext, flags=re.M)  # noqa`

Then, when I compile my document (which has a theorem environment), I get a latex "Environment theorem undefined” warning. I fixed this by adding the following 2 lines to the latex file:

```
\usepackage{amsthm}
\newtheorem{theorem}{Theorem}
```

I also get the package author's (j.f. bercher) name above the TOC on the first page, and then my name and title (which are the name and title of the jupyter notebook) on the second page. 

I'll try to fix these things and submit a pull request when I have some time.
