### ISSUE TITLE
ModuleNotFoundError: No module named 'latex_envs'

### ISSUE THREAD

**Issue by mebden** [jfbercher/jupyter_latex_envs#54]
Trying to position text exactly in a Jupyter notebook markdown cell, I'd like to use the $\vspace{-2cm}$ Latex syntax.

I read [here](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/latex_envs/README.html) that it's possible to extend the little amount of Latex available in Jupyter. However, on step 2 of the installation I get an error:
```
jupyter nbextension install --py latex_envs
Traceback (most recent call last):
  File "/Users/macuser/opt/anaconda3/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 211, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/notebook/nbextensions.py", line 1122, in _get_nbextension_metadata
    m = import_item(module)
  File "/Users/macuser/opt/anaconda3/lib/python3.7/site-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'latex_envs'
```
Any thoughts on how to resolve this error, or alternatives to \vspace{-2cm} in the default Jupyter setup? Thank you.

**Comment by jfbercher** [comment]
It seems to be a path issue, independent of the extension itself.
Try to figure where the latex_env package was installed on the first step
and check if it can be imported from python. If not, move the package or
change the pythonpath.
I see that you are using anaconda. If you installed via pip, try to use
conda instead.

**Comment by mebden** [comment]
Thanks! The conda install worked great.
